Fix: 새로운 인스턴스 실행 전 포트 종료 확인

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,9 +48,15 @@ jobs:
       - name: Deploy on GCP instance
         run: |
           ssh -o StrictHostKeyChecking=no beamt348@${{ secrets.GCP_HOST }} << 'EOF'
-            echo "Stopping existing application..."
-            pkill -f 'java -jar' || true
-            sleep 10  # 애플리케이션 종료 대기 시간
+            echo "Stopping existing application using Actuator..."
+            if curl -s -X POST http://localhost:8080/actuator/shutdown; then
+              echo "Spring Boot application shutdown successfully."
+              sleep 10  # 애플리케이션 종료 대기 시간
+            else
+              echo "Failed to shutdown Spring Boot application or it was not running. Attempting to kill the process..."
+              pkill -f 'java -jar' || true
+              sleep 10  # 애플리케이션 종료 대기 시간
+            fi
           
             echo "Checking if port 8080 is free..."
             while sudo lsof -t -i tcp:8080; do
@@ -61,3 +67,4 @@ jobs:
             echo "Starting new application instance..."
             nohup java -jar /home/beamt348/app/teambeam-0.0.1-SNAPSHOT.jar --spring.profiles.active=gcp > /home/beamt348/app/app.log 2>&1 &
           EOF
+
